// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesOrderDataManager.DAL.Context;

#nullable disable

namespace SalesOrderDataManager.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231228073752_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesOrderDataManager.DAL.Entities.SalesOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SalesOrders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5eca5808-4f44-4c4c-b481-72d2bdf24203"),
                            Name = "New York Building 1",
                            State = "NY"
                        },
                        new
                        {
                            Id = new Guid("5b32effd-2636-4cab-8ac9-3258c746aa53"),
                            Name = "California Hotel AJK",
                            State = "CA"
                        });
                });

            modelBuilder.Entity("SalesOrderDataManager.DAL.Entities.SubElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Element")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<Guid?>("WindowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WindowId");

                    b.ToTable("SubElements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("32bccc93-e4ac-450f-82de-b521941c0640"),
                            Element = "1",
                            Height = 1850,
                            Type = "Doors",
                            Width = 1200,
                            WindowId = new Guid("5eca5808-4f44-4c4c-b481-72d2bdf24203")
                        },
                        new
                        {
                            Id = new Guid("03027fbc-d76e-41cb-873b-c79bdde5f7d2"),
                            Element = "2",
                            Height = 1850,
                            Type = "Window",
                            Width = 800,
                            WindowId = new Guid("5eca5808-4f44-4c4c-b481-72d2bdf24203")
                        },
                        new
                        {
                            Id = new Guid("69d727b9-852f-4018-b1eb-acc16a37034d"),
                            Element = "3",
                            Height = 1850,
                            Type = "Window",
                            Width = 700,
                            WindowId = new Guid("5eca5808-4f44-4c4c-b481-72d2bdf24203")
                        },
                        new
                        {
                            Id = new Guid("49b11a88-762d-429e-ac8f-9ef1ff4c012b"),
                            Element = "1",
                            Height = 2000,
                            Type = "Window",
                            Width = 1500,
                            WindowId = new Guid("4ffa6173-bc0b-4d3b-9a68-65227dd1bc8b")
                        },
                        new
                        {
                            Id = new Guid("607a7e2b-25c2-478d-9d74-2cd17db2cebe"),
                            Element = "1",
                            Height = 2200,
                            Type = "Doors",
                            Width = 1400,
                            WindowId = new Guid("5eca5808-545a-4c4c-b481-72d2bdf24203")
                        },
                        new
                        {
                            Id = new Guid("a3cc6050-04f4-4e1a-9292-31fc05b26293"),
                            Element = "2",
                            Height = 2200,
                            Type = "Window",
                            Width = 600,
                            WindowId = new Guid("5eca5808-545a-4c4c-b481-72d2bdf24203")
                        },
                        new
                        {
                            Id = new Guid("79265336-bfd2-41eb-873c-eb34616cbd71"),
                            Element = "1",
                            Height = 2000,
                            Type = "Window",
                            Width = 1500,
                            WindowId = new Guid("6eca5808-4f44-4c4c-b481-72d2bdf24203")
                        },
                        new
                        {
                            Id = new Guid("e467b989-ea10-4541-8d39-43e1e87f03a9"),
                            Element = "1",
                            Height = 2000,
                            Type = "Window",
                            Width = 1500,
                            WindowId = new Guid("6eca5808-4f44-4c4c-b481-72d2bdf24203")
                        });
                });

            modelBuilder.Entity("SalesOrderDataManager.DAL.Entities.Window", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityOfWindows")
                        .HasColumnType("int");

                    b.Property<int>("TotalSubElements")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Windows");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5eca5808-4f44-4c4c-b481-72d2bdf24203"),
                            Name = "A51",
                            OrderId = new Guid("5eca5808-4f44-4c4c-b481-72d2bdf24203"),
                            QuantityOfWindows = 4,
                            TotalSubElements = 3
                        },
                        new
                        {
                            Id = new Guid("4ffa6173-bc0b-4d3b-9a68-65227dd1bc8b"),
                            Name = "C Zone 5",
                            OrderId = new Guid("5eca5808-4f44-4c4c-b481-72d2bdf24203"),
                            QuantityOfWindows = 2,
                            TotalSubElements = 1
                        },
                        new
                        {
                            Id = new Guid("5eca5808-545a-4c4c-b481-72d2bdf24203"),
                            Name = "GLB",
                            OrderId = new Guid("5b32effd-2636-4cab-8ac9-3258c746aa53"),
                            QuantityOfWindows = 3,
                            TotalSubElements = 2
                        },
                        new
                        {
                            Id = new Guid("6eca5808-4f44-4c4c-b481-72d2bdf24203"),
                            Name = "OHF",
                            OrderId = new Guid("5b32effd-2636-4cab-8ac9-3258c746aa53"),
                            QuantityOfWindows = 10,
                            TotalSubElements = 2
                        });
                });

            modelBuilder.Entity("SalesOrderDataManager.DAL.Entities.SubElement", b =>
                {
                    b.HasOne("SalesOrderDataManager.DAL.Entities.Window", "Window")
                        .WithMany("SubElements")
                        .HasForeignKey("WindowId");

                    b.Navigation("Window");
                });

            modelBuilder.Entity("SalesOrderDataManager.DAL.Entities.Window", b =>
                {
                    b.HasOne("SalesOrderDataManager.DAL.Entities.SalesOrder", "Order")
                        .WithMany("Windows")
                        .HasForeignKey("OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SalesOrderDataManager.DAL.Entities.SalesOrder", b =>
                {
                    b.Navigation("Windows");
                });

            modelBuilder.Entity("SalesOrderDataManager.DAL.Entities.Window", b =>
                {
                    b.Navigation("SubElements");
                });
#pragma warning restore 612, 618
        }
    }
}
